version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent
  rso-rents:
    image: jp8874/rso-teamlj-rents:2.5
    ports:
    - 8081:8081
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://172.17.0.1:5433/rent
      KUMULUZEE_DATASOURCES0_USERNAME: postgres
      KUMULUZEE_DATASOURCES0_PASSWORD: postgres
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://172.17.0.1:2379
    depends_on:
    - postgres

