kumuluzee:
  name: rso-rents
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/RentsDS
      connection-url: jdbc:postgresql://35.228.47.159:5432/rent
      username: rso
      password: rso
      #connection-url: jdbc:postgresql://192.168.1.5:5433/rent
      #username: postgres
      #password: postgres
      max-pool-size: 20
  discovery:
      etcd:
        hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: rent-endpoint
      url-pattern: /v1/rents/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/RentsDS
      disk-space-health-check:
        threshold: 100000000
        etcd-health-check:
          connection-url: http://localhost:2379/health
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="rents">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="5d872f8f-f02a-4f15-b966-e8796ff99a28-ls.logit.io"
                                port="13221" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
